# tar1090 only - port 8090
server.username  = "http"
server.groupname = "http"
server.document-root = "/usr/local/share/tar1090/html"
server.port = 8090

server.modules += ("mod_alias")
alias.url = ( "/data/" => "/run/readsb/" )
index-file.names = ( "index.html" )
